# This is a basic workflow to help you get started with Actions

name: Build image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    #branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build_Image:
    name: Configure source tree
    
    # The type of runner that the job will run on
    runs-on: self-hosted

    container: 
      image: ghcr.io/linuxianer99/ovbuild-container-kas
      options: --user 1000
      env: 
        KAS_TARGET: sensord
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Buildup source tree
        run: kas checkout openvario.yml
        
      - name: Build sensord
        run: kas build openvario.yml
